import React from 'react'

export default function About() {
  return (
    <>
        <div className="container my-5">
            <h2>About Us</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Orci nulla pellentesque dignissim enim sit. Orci nulla pellentesque dignissim enim sit. Lorem sed risus ultricies tristique nulla aliquet. Massa enim nec dui nunc mattis enim ut tellus elementum. Vitae purus faucibus ornare suspendisse sed. Arcu risus quis varius quam. Fusce ut placerat orci nulla. Hendrerit dolor magna eget est lorem ipsum. Rhoncus mattis rhoncus urna neque. Auctor elit sed vulputate mi sit. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. In est ante in nibh mauris cursus mattis molestie.</p>
            <p>Sapien nec sagittis aliquam malesuada bibendum. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Gravida in fermentum et sollicitudin. Dictum sit amet justo donec enim. Tellus mauris a diam maecenas sed enim. Ante metus dictum at tempor commodo ullamcorper a. Ac turpis egestas maecenas pharetra. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Nec nam aliquam sem et tortor. Ante in nibh mauris cursus mattis molestie a. Potenti nullam ac tortor vitae purus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Orci nulla pellentesque dignissim enim sit. Orci nulla pellentesque dignissim enim sit. Lorem sed risus ultricies tristique nulla aliquet. Massa enim nec dui nunc mattis enim ut tellus elementum. Vitae purus faucibus ornare suspendisse sed. Arcu risus quis varius quam. Fusce ut placerat orci nulla. Hendrerit dolor magna eget est lorem ipsum. Rhoncus mattis rhoncus urna neque. Auctor elit sed vulputate mi sit. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. In est ante in nibh mauris cursus mattis molestie.</p>
            <p>Sapien nec sagittis aliquam malesuada bibendum. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Gravida in fermentum et sollicitudin. Dictum sit amet justo donec enim. Tellus mauris a diam maecenas sed enim. Ante metus dictum at tempor commodo ullamcorper a. Ac turpis egestas maecenas pharetra. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Nec nam aliquam sem et tortor. Ante in nibh mauris cursus mattis molestie a. Potenti nullam ac tortor vitae purus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Orci nulla pellentesque dignissim enim sit. Orci nulla pellentesque dignissim enim sit. Lorem sed risus ultricies tristique nulla aliquet. Massa enim nec dui nunc mattis enim ut tellus elementum. Vitae purus faucibus ornare suspendisse sed. Arcu risus quis varius quam. Fusce ut placerat orci nulla. Hendrerit dolor magna eget est lorem ipsum. Rhoncus mattis rhoncus urna neque. Auctor elit sed vulputate mi sit. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. In est ante in nibh mauris cursus mattis molestie.</p>
            <p>Sapien nec sagittis aliquam malesuada bibendum. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Gravida in fermentum et sollicitudin. Dictum sit amet justo donec enim. Tellus mauris a diam maecenas sed enim. Ante metus dictum at tempor commodo ullamcorper a. Ac turpis egestas maecenas pharetra. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Nec nam aliquam sem et tortor. Ante in nibh mauris cursus mattis molestie a. Potenti nullam ac tortor vitae purus.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Orci nulla pellentesque dignissim enim sit. Orci nulla pellentesque dignissim enim sit. Lorem sed risus ultricies tristique nulla aliquet. Massa enim nec dui nunc mattis enim ut tellus elementum. Vitae purus faucibus ornare suspendisse sed. Arcu risus quis varius quam. Fusce ut placerat orci nulla. Hendrerit dolor magna eget est lorem ipsum. Rhoncus mattis rhoncus urna neque. Auctor elit sed vulputate mi sit. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. In est ante in nibh mauris cursus mattis molestie.</p>
            <p>Sapien nec sagittis aliquam malesuada bibendum. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Gravida in fermentum et sollicitudin. Dictum sit amet justo donec enim. Tellus mauris a diam maecenas sed enim. Ante metus dictum at tempor commodo ullamcorper a. Ac turpis egestas maecenas pharetra. Mauris pellentesque pulvinar pellentesque habitant morbi tristique. Nec nam aliquam sem et tortor. Ante in nibh mauris cursus mattis molestie a. Potenti nullam ac tortor vitae purus.</p>
        </div>
    </>
  )
}
